candlestick:
  granularity: 'M1'
  count: 5000


instrument_precision:
  EUR_USD: 4
  AUD_USD: 4
  NZD_USD: 4
  GBP_USD: 4
  GBP_JPY: 2
  USD_JPY: 2
  EUR_JPY: 2

stop_loss:
  EUR_USD: 0.0001
  AUD_USD: 0.0001
  NZD_USD: 0.0001
  GBP_USD: 0.0001
  GBP_JPY: 0.01
  USD_JPY: 0.01
  EUR_JPY: 0.01

take_profit:
  EUR_USD: 0.0002
  AUD_USD: 0.0002
  NZD_USD: 0.0002
  GBP_USD: 0.0002
  GBP_JPY: 0.02
  USD_JPY: 0.02
  EUR_JPY: 0.02